site_name: Koswat
site_url: https://deltares.github.io/Koswat/
repo_url: https://github.com/Deltares/koswat
repo_name: Deltares/koswat
copyright: Copyright &copy; 2026 Deltares

theme:
  name: readthedocs
  highlightjs: true
  include_homepage_in_sidebar: true

extra:
  authoremail: carles.sorianoperez@deltares.nl
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Deltares/koswat
      name: Source code

watch:
    - koswat/

plugins:
  - search
  - autorefs
  - mike
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # docstring_style: sphinx
            show_root_toc_entry: false
            show_source: false
            show_signature_annotations: true
            heading_level: 3
            show_category_heading: false
            group_by_category: false
            inherited_members: false
use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

