[tool.poetry]
name = "koswat"
version = "0.6.0"
description = ""
authors = ["Carles S. Soriano Pérez <carles.sorianoperez@deltares.nl>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/Deltares/koswat"
documentation = ""
classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
  'Natural Language :: English',
  'Programming Language :: Python :: 3',
]

[tool.poetry.dependencies]
python = "^3.10"
future = "^0.18.2"
click = "^8.1.3"
matplotlib = "^3.6.0"
pyshp = "^2.3.1"
shapely = "^1.8.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
black = "^22.8.0"
isort = "^5.10.1"
commitizen = "^2.35.0"
mypy = "^0.971"
termcolor = "^2.0.1"
coverage = "^6.4.4"


[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | \.virtualenvs
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.commitizen]
name = "cz_conventional_commits"
changelog_file = "docs/changelog.md"
update_changelog_on_bump = true
version = "0.6.0"
tag_format = "v$major.$minor.$patch"
version_files= [
    "koswat/__init__.py",
    "pyproject.toml:version",]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
