"""
                    GNU GENERAL PUBLIC LICENSE
                      Version 3, 29 June 2007

    KOSWAT, from the dutch combination of words `Kosts-Wat` (what are the costs)
    Copyright (C) 2024 Stichting Deltares

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import logging

import click

from koswat.koswat_handler import KoswatHandler


### Below is the documentation for the commandline interface, see the CLICK-package.
@click.command()
@click.option("--input_file", default=None, help="Full path to the config input file.")
@click.option(
    "--log_output",
    default=None,
    help="Directory location where to generate the Koswat log file.",
)
def run_analysis(input_file: str, log_output: str):
    """
    CLI call to execute a Koswat analysis given a settings files (`input_file`). The log is generated by default in the execute path, unless otherwise specified in the `log_output` argument.

    Args:
        input_file (str): Location of the `*.json` file containing the execution settings for Koswat.
        log_output (str): Optional argument to specify where will be created the `koswat.log` file.
    """
    with KoswatHandler(log_output) as _handler:
        _handler.run_analysis(input_file)


if __name__ == "__main__":
    try:
        run_analysis()
    except Exception as e_info:
        logging.error(str(e_info))
