"""
                    GNU GENERAL PUBLIC LICENSE
                      Version 3, 29 June 2007

    KOSWAT, from the dutch combination of words `Kosts-Wat` (what are the costs)
    Copyright (C) 2025 Stichting Deltares

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from geopandas import GeoDataFrame

from koswat.core.io.file_object_model_protocol import FileObjectModelProtocol


class ClusterGeoDataFrameOutputFom(FileObjectModelProtocol):
    """
    Data structure to wrap the output generated by `ClusterCollectionShpFom.generate_geodataframes`.
    """

    base_layer: GeoDataFrame | None
    initial_state: GeoDataFrame | None
    new_state: GeoDataFrame | None

    def __init__(self, gdf_tuples: tuple[GeoDataFrame]):
        self.base_layer = None
        self.initial_state = None
        self.new_state = None

        if not gdf_tuples:
            return
        self.base_layer = gdf_tuples[0]
        self.initial_state = gdf_tuples[1]
        self.new_state = gdf_tuples[2]

    def is_valid(self) -> bool:
        """
        Checks that all `GeoDataFrame` properties are set.

        Returns:
            bool: Validation result.
        """

        def validate_gdf(gdf: GeoDataFrame | None) -> bool:
            return gdf is not None

        return all(
            map(validate_gdf, [self.base_layer, self.initial_state, self.new_state])
        )
