name: cd-rc-bumper

on:
  push:
    branches: [ "release/**" ]

env:
  GH_TOKEN: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

jobs:
  bump-rc-version:
    name: "Automatic release candidate bumping"
    if: ${{ contains(github.ref, 'refs/heads/release/') && (!startsWith(github.event.head_commit.message, 'bump'))}}
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}
         
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Set relevant variable values
        run: |
          echo "PAT_USER=$(gh api user | jq -r '.login')" >> "$GITHUB_ENV"
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | cut -d "/" -f 2 | tr "-" " " | sed 's/.*/\u&/')" >> "$GITHUB_ENV"
  
      - name: Set GIT identity
        run: |
          git config --global user.name '${{ env.PAT_USER }}'
          git config --global user.email '${{ env.PAT_USER }}@users.noreply.github.com'

      # - name: Bump project versions
      #   run: pixi run  version_bumper.py --release-candidate --release-title '${{ env.BRANCH_NAME }}'
      - name: Bump project versions
        run: pixi run bump-rc --allow-no-commit

      - name: Push changes
        run: |
          git push --force
  
  creates-pr:
    name: "Create new pull-request"
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write
    needs: bump-versions
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

      - name: Set relevant variable values
        run: |
          echo "PAT_USER=$(gh api user | jq -r '.login')" >> "$GITHUB_ENV"
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | cut -d "/" -f 2 | tr "-" " " | sed 's/.*/\u&/')" >> "$GITHUB_ENV"

      - name: Set GIT identity
        run: |
          git config --global user.name '${{ env.PAT_USER }}'
          git config --global user.email '${{ env.PAT_USER }}@users.noreply.github.com'

      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --repo "$GITHUB_REPOSITORY" --label "release" --json title --jq 'length')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
        
      - name: Create Pull Request
        if: '!steps.check.outputs.skip'
        run: |
          gh pr create --title "release: '${{ env.BRANCH_NAME }}'" --body-file ".github/release_template.md" --label "release"