name: cd-version-bumper

on:
  push:
    tags: [ "v*" ]

env:
  GH_TOKEN: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

jobs:
  generate-release:
    name: "Generate release from bump release tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

      - name: Set release variables
        run: |
          echo "RELEASE_TAG=${{ github.ref_name }}" >> "$GITHUB_ENV"
          echo "OLD_RELEASE_TAG=$(git tag --sort=committerdate | grep -o 'v.*' | tail -2 | head -1)" >> "$GITHUB_ENV"

      - name: Check if pre-release
        run: |
          if echo "${{ github.ref_name }}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+rc'; then
            echo "IS_PRERELEASE=true" >> "$GITHUB_ENV"
          else
            echo "IS_PRERELEASE=false" >> "$GITHUB_ENV"
          fi

      - name: Set release title
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%-m')
          QUARTER=$(( (MONTH - 1) / 3 + 1 ))
          CLEAN_VERSION=$(echo "${{ github.ref_name }}" | sed 's/rc[0-9]*//')

          if [ "${{ env.IS_PRERELEASE }}" == "true" ]; then
            echo "RELEASE_TITLE=${YEAR}.Q${QUARTER} ${CLEAN_VERSION} prerelease" >> "$GITHUB_ENV"
          else
            echo "RELEASE_TITLE=${YEAR}.Q${QUARTER} ${{ github.ref_name }} release" >> "$GITHUB_ENV"
          fi

      - name: Generate release (pre-release)
        if: env.IS_PRERELEASE == 'true'
        run: |
          gh release create '${{ env.RELEASE_TAG }}' \
            --verify-tag \
            --prerelease \
            --title '${{ env.RELEASE_TITLE }}' \
            --generate-notes \
            --notes-start-tag '${{ env.OLD_RELEASE_TAG }}'
      - name: Generate release (stable)
        if: env.IS_PRERELEASE == 'false'
        run: |
          gh release create '${{ env.RELEASE_TAG }}' \
            --verify-tag \
            --latest \
            --title '${{ env.RELEASE_TITLE }}' \
            --generate-notes \
            --notes-start-tag '${{ env.OLD_RELEASE_TAG }}'