name: cd-release-bumper

on:
  push:
    branches: [ master ]

env:
  GH_TOKEN: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

jobs:
  bump-release:
    if: "${{ startsWith(github.event.head_commit.message, 'release') }}"
    name: "Bumps release candidate into formal release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

      - name: Set relevant variable values
        run: |
          echo "PAT_USER=$(gh api user | jq -r '.login')" >> "$GITHUB_ENV"
          RELEASE_TITLE=$(git log -1 --pretty=format:%s | cut -d ':' -f 2 | awk '{$1=$1;print}')
          echo "RELEASE_COMMIT=release: ${RELEASE_TITLE}" >> "$GITHUB_ENV"

      - name: Set GIT identity
        run: |
          git config --global user.name '${{ env.PAT_USER }}'
          git config --global user.email '${{ env.PAT_USER }}@users.noreply.github.com'

      - name: Bump project versions
        run: pixi run bump --allow-no-commit --bump-message '${{ env.RELEASE_COMMIT }}'

      - name: Push changes
        run: |
          git push --force && git push --tags --force