name: ci-install-package

on:
  push:
    branches:
      - master
      - fix/254-migrate-from-poetry-to-pixi
    
jobs:
  install-package:
    if: "${{ (!startsWith(github.event.head_commit.message, 'chore: autoformat isort & black')) && (!startsWith(github.event.head_commit.message, 'bump:')) }}"
    strategy:
      fail-fast: false
      matrix:
        environment: [py311, py312, py313]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
          environments: ${{ matrix.environment }}

      - name: Install Dependencies
        run: pixi install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build package
        run: pixi run pypi-build
        if: steps.cache.outputs.cache-hit != 'true'
        