name: "GitHub Pages documentation"
on:
  push:
    branches: [ master ]

permissions:
    contents: write

jobs:
  docs:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: Build (and deploy) documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
      
      - run: pixi run mkdocs gh-deploy --force