name: "GitHub Pages documentation"
on:
  push:
    branches: [ master ]

permissions:
    contents: write

jobs:
  docs:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: Build (and deploy) documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          # channels: conda-forge, nodefaults
          # channel-priority: strict
          environment-file: .devcontainer/environment.yml
          activate-environment: koswat_env

      - name: Install dependencies
        run: poetry install --without dev,test

      - run: poetry run mkdocs gh-deploy --force